apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  labels:
    app: timescaledb
spec:
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb:2.5.1-pg14
          ports:
            - name: timescaledb
              protocol: TCP
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timescaledb-password
                  key: password
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: timescaledb-pvc
  strategy:
    type: Recreate
